# Basic Info
title: Jo Yuan
email: jmehsieh@gmail.com
description: "Hi, I am Jo Yuan."
baseurl: ""
url: "http://jmehsieh.com"
permalink: ":categories/:year-:month-:day-:title/"

# Sass
sass:
  style: :compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
